# Site settings
description: > # this means to ignore newlines until "baseurl:"
  fffabs &copy 2015 - go create!
title: Jonas Greitemann
email: jgreitemann@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jgreitemann.github.io" # the base hostname & protocol for your site
plugins: [jekyll-paginate]

twitter:
  username: jg424
github:
  owner_name:  jgreitemann
  owner_url:   "https://github.com/jgreitemann"
telegram:
  username: jgreitemann
lastfm:
  username: jgreitemann
stackexchange:
  userid: 3028048
  username: jonas
arxiv:
  search_url: "https://arxiv.org/find/cond-mat/1/au:+Greitemann_J/0/1/0/all/0/1"

collections:
  publications:
    output: true

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge
kramdown:
  math_engine: mathjax

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
